import Navbar from "@/components/Navbar";
import Hero from "@/components/sections/Hero";
import { Box, Container, Text } from "@chakra-ui/react";
import Head from "next/head";
import { Element } from "react-scroll";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxW="container.lg"
        px={{ base: 6, md: 4 }}
      >
        <Navbar />
        {/* Hero */}
        <Hero />
        <Box>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text>Scrollea más abajo...</Text>
          <Text id="test">Has llegado</Text>
        </Box>
        {/* Feature */}
        {/* Process */}
        {/* Princing */}
        {/* FAQ */}
        {/* Contact */}
        {/* Footer */}
      </Container>
    </>
  );
}
